/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: luis001 (https://sketchfab.com/luis001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bouquet-5-1eed2b97155e4397ac4a03fc7dfcc899
Title: Bouquet - 5
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export  default function Minibouquet(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('minibouquet/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={10000}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Armature_6"
                position={[2.436, 0.114, 0.001]}
                rotation={[3.053, 0.292, 0.367]}
                scale={0.01}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Lily_Tentacles}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.T_Flowers}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Fill}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.T_Flowers}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.Lily_Tentacles}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_14"
                    geometry={nodes.Object_14.geometry}
                    material={materials.Bulb}
                    skeleton={nodes.Object_14.skeleton}
                  />
                  <skinnedMesh
                    name="Object_16"
                    geometry={nodes.Object_16.geometry}
                    material={materials.Leaves}
                    skeleton={nodes.Object_16.skeleton}
                  />
                  <skinnedMesh
                    name="Object_18"
                    geometry={nodes.Object_18.geometry}
                    material={materials.Bouquet}
                    skeleton={nodes.Object_18.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.Ribbon}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <group name="Branches_1" />
                  <group name="Fill_2" />
                  <group name="Flowers_3" />
                  <group name="Stems_4" />
                  <group name="Wrapping_5" />
                </group>
              </group>
              <group name="Lightrays_8" rotation={[0, Math.PI / 2, 0]} scale={0} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('minibouquet/scene.gltf')
