/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tulips-bouquet-2bb621c42485443fa87e19badff916e4
Title: Tulips bouquet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Tulips(props) {
  const { nodes, materials } = useGLTF('/tulips_bouquet/scene.gltf')
  
   const tulRef = useRef()
  
    useFrame(() => {
      if (tulRef.current) {
        tulRef.current.rotation.y += 0.01; // Adjust speed here
      }
    });

  return (
    <group {...props} dispose={null} ref={tulRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1} position={[0,0,0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.material_0}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.material_0}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tulips_bouquet/scene.gltf')